# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent_v2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from isolate.connections.grpc.definitions import common_pb2 as common__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0e\x61gent_v2.proto\x1a\x0c\x63ommon.proto"8\n\x11\x43reateTaskRequest\x12#\n\x08\x66unction\x18\x01 \x01(\x0b\x32\x11.SerializedObject"%\n\x12\x43reateTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t"#\n\x10\x43heckTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t"c\n\x11\x43heckTaskResponse\x12\x1b\n\x06status\x18\x01 \x01(\x0e\x32\x0b.TaskStatus\x12&\n\x06result\x18\x02 \x01(\x0b\x32\x11.SerializedObjectH\x00\x88\x01\x01\x42\t\n\x07_result"$\n\x11\x43\x61ncelTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t"(\n\x12\x43\x61ncelTaskResponse\x12\x12\n\ndid_cancel\x18\x01 \x01(\x08"\x14\n\x12\x41gentStatusRequest";\n\x13\x41gentStatusResponse\x12\x12\n\nnum_queued\x18\x01 \x01(\x05\x12\x10\n\x08idle_for\x18\x02 \x01(\x02*4\n\nTaskStatus\x12\n\n\x06QUEUED\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\r\n\tCOMPLETED\x10\x02\x32\xed\x01\n\x07\x41gentV2\x12\x37\n\nCreateTask\x12\x12.CreateTaskRequest\x1a\x13.CreateTaskResponse"\x00\x12\x34\n\tCheckTask\x12\x11.CheckTaskRequest\x1a\x12.CheckTaskResponse"\x00\x12\x37\n\nCancelTask\x12\x12.CancelTaskRequest\x1a\x13.CancelTaskResponse"\x00\x12:\n\x0b\x41gentStatus\x12\x13.AgentStatusRequest\x1a\x14.AgentStatusResponse"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "agent_v2_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _TASKSTATUS._serialized_start = 430
    _TASKSTATUS._serialized_end = 482
    _CREATETASKREQUEST._serialized_start = 32
    _CREATETASKREQUEST._serialized_end = 88
    _CREATETASKRESPONSE._serialized_start = 90
    _CREATETASKRESPONSE._serialized_end = 127
    _CHECKTASKREQUEST._serialized_start = 129
    _CHECKTASKREQUEST._serialized_end = 164
    _CHECKTASKRESPONSE._serialized_start = 166
    _CHECKTASKRESPONSE._serialized_end = 265
    _CANCELTASKREQUEST._serialized_start = 267
    _CANCELTASKREQUEST._serialized_end = 303
    _CANCELTASKRESPONSE._serialized_start = 305
    _CANCELTASKRESPONSE._serialized_end = 345
    _AGENTSTATUSREQUEST._serialized_start = 347
    _AGENTSTATUSREQUEST._serialized_end = 367
    _AGENTSTATUSRESPONSE._serialized_start = 369
    _AGENTSTATUSRESPONSE._serialized_end = 428
    _AGENTV2._serialized_start = 485
    _AGENTV2._serialized_end = 722
# @@protoc_insertion_point(module_scope)
