"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
from isolate.connections.grpc.definitions import common_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class FunctionCall(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FUNCTION_FIELD_NUMBER: builtins.int
    SETUP_FUNC_FIELD_NUMBER: builtins.int
    TEARDOWN_FUNC_FIELD_NUMBER: builtins.int
    @property
    def function(self) -> common_pb2.SerializedObject:
        """The function to execute and return the results to."""

    @property
    def setup_func(self) -> common_pb2.SerializedObject:
        """Optionally the setup function which will be passed
        as the first argument to the given function. This
        has to be an idempotent step since the result for
        this executable will be cached.
        """

    @property
    def teardown_func(self) -> common_pb2.SerializedObject: ...
    def __init__(
        self,
        *,
        function: common_pb2.SerializedObject | None = ...,
        setup_func: common_pb2.SerializedObject | None = ...,
        teardown_func: common_pb2.SerializedObject | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_setup_func", b"_setup_func", "_teardown_func", b"_teardown_func", "function", b"function", "setup_func", b"setup_func", "teardown_func", b"teardown_func"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_setup_func", b"_setup_func", "_teardown_func", b"_teardown_func", "function", b"function", "setup_func", b"setup_func", "teardown_func", b"teardown_func"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_setup_func", b"_setup_func"]) -> typing.Literal["setup_func"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_teardown_func", b"_teardown_func"]) -> typing.Literal["teardown_func"] | None: ...

global___FunctionCall = FunctionCall
