# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import bridge_pb2 as bridge__pb2


class BridgeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Run = channel.unary_stream(
            "/Bridge/Run",
            request_serializer=bridge__pb2.BoundFunction.SerializeToString,
            response_deserializer=bridge__pb2.PartialRunResult.FromString,
        )


class BridgeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Run(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_BridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Run": grpc.unary_stream_rpc_method_handler(
            servicer.Run,
            request_deserializer=bridge__pb2.BoundFunction.FromString,
            response_serializer=bridge__pb2.PartialRunResult.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "Bridge", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Bridge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Run(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/Bridge/Run",
            bridge__pb2.BoundFunction.SerializeToString,
            bridge__pb2.PartialRunResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
