# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bridge.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0c\x62ridge.proto\x1a\x1cgoogle/protobuf/struct.proto"a\n\rBoundFunction\x12+\n\x0b\x65nvironment\x18\x01 \x01(\x0b\x32\x16.EnvironmentDefinition\x12#\n\x08\x66unction\x18\x02 \x01(\x0b\x32\x11.SerializedObject"U\n\x15\x45nvironmentDefinition\x12\x0c\n\x04kind\x18\x01 \x01(\t\x12.\n\rconfiguration\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct"Z\n\x10SerializedObject\x12\x1c\n\x14serialization_method\x18\x01 \x01(\t\x12\x12\n\ndefinition\x18\x02 \x01(\x0c\x12\x14\n\x0cis_exception\x18\x03 \x01(\x08"m\n\x10PartialRunResult\x12\x13\n\x0bis_complete\x18\x01 \x01(\x08\x12\x11\n\x03log\x18\x02 \x03(\x0b\x32\x04.Log\x12&\n\x06result\x18\x03 \x01(\x0b\x32\x11.SerializedObjectH\x00\x88\x01\x01\x42\t\n\x07_result"L\n\x03Log\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x1a\n\x06source\x18\x02 \x01(\x0e\x32\n.LogSource\x12\x18\n\x05level\x18\x03 \x01(\x0e\x32\t.LogLevel*.\n\tLogSource\x12\x0b\n\x07\x42UILDER\x10\x00\x12\n\n\x06\x42RIDGE\x10\x01\x12\x08\n\x04USER\x10\x02*Z\n\x08LogLevel\x12\t\n\x05TRACE\x10\x00\x12\t\n\x05\x44\x45\x42UG\x10\x01\x12\x08\n\x04INFO\x10\x02\x12\x0b\n\x07WARNING\x10\x03\x12\t\n\x05\x45RROR\x10\x04\x12\n\n\x06STDOUT\x10\x05\x12\n\n\x06STDERR\x10\x06\x32\x36\n\x06\x42ridge\x12,\n\x03Run\x12\x0e.BoundFunction\x1a\x11.PartialRunResult"\x00\x30\x01\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "bridge_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _LOGSOURCE._serialized_start = 513
    _LOGSOURCE._serialized_end = 559
    _LOGLEVEL._serialized_start = 561
    _LOGLEVEL._serialized_end = 651
    _BOUNDFUNCTION._serialized_start = 46
    _BOUNDFUNCTION._serialized_end = 143
    _ENVIRONMENTDEFINITION._serialized_start = 145
    _ENVIRONMENTDEFINITION._serialized_end = 230
    _SERIALIZEDOBJECT._serialized_start = 232
    _SERIALIZEDOBJECT._serialized_end = 322
    _PARTIALRUNRESULT._serialized_start = 324
    _PARTIALRUNRESULT._serialized_end = 433
    _LOG._serialized_start = 435
    _LOG._serialized_end = 511
    _BRIDGE._serialized_start = 653
    _BRIDGE._serialized_end = 707
# @@protoc_insertion_point(module_scope)
