# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from isolate.server_v2.definitions import common_pb2 as common__pb2
from isolate.server_v2.definitions import controller_pb2 as controller__pb2


class ControllerBridgeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
            "/ControllerBridge/Connect",
            request_serializer=common__pb2.PartialRunResult.SerializeToString,
            response_deserializer=controller__pb2.Task.FromString,
        )


class ControllerBridgeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request_iterator, context):
        """A bi-directional RPC channel for controller and agent to communicate on.
        Every time there is a new task (e.g. a run() operation), the controller
        will send it through the already established channel and the agent will
        respond with the result.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ControllerBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Connect": grpc.stream_stream_rpc_method_handler(
            servicer.Connect,
            request_deserializer=common__pb2.PartialRunResult.FromString,
            response_serializer=controller__pb2.Task.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ControllerBridge", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ControllerBridge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/ControllerBridge/Connect",
            common__pb2.PartialRunResult.SerializeToString,
            controller__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
