# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controller.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10\x63ontroller.proto\x1a\x0c\x63ommon.proto"+\n\x04Task\x12#\n\x08\x66unction\x18\x01 \x01(\x0b\x32\x11.SerializedObject2=\n\x10\x43ontrollerBridge\x12)\n\x07\x43onnect\x12\x11.PartialRunResult\x1a\x05.Task"\x00(\x01\x30\x01\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "controller_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _TASK._serialized_start = 34
    _TASK._serialized_end = 77
    _CONTROLLERBRIDGE._serialized_start = 79
    _CONTROLLERBRIDGE._serialized_end = 140
# @@protoc_insertion_point(module_scope)
